### PR TITLE
Fix #17, #18 - Fix wrong deps on `useProcessJson` and layout `ReactorEditor` on container resizing

### LINKED ISSUE #17: Output data is not changes when `Reactor` code is changed while URL mode
# Browser 

Unrelated

# Detailed

## What happened?

- Output value is not changed

## How can I reproduce?

- [Link](https://phryxia.github.io/json-lense/?data=N4IglgdgDgrgLiAXAbQIwBoBM6DM6As6ArALrogBOApgIYDGcA9hQMKMAmVSIA9DwAQARRvwiM4-OgAsaEAOZV+zftQC2jAG6K4UsAGd+esHIg04MagEIAOhDqMIeiXAqy9AM2arE-AGo0AGzB2ACVaBmUAXn4ACnYzGh8AFQBPKCoASn5IgD5+YFt+fj5+QBdxwBiawBee0sAXLv5ARkHAV5rAHVXAUJrAD+7ClSpzCgh+eLgaADpVGigYgA9svMx+ACp+SYzbAF8QVaA)
- Change `2` in the `Reactor` code into `3`
- Check output value

### PR DESCRIPTION
**Pull request by Phryxia**
- #17 
- #18 

`i_love_collei`

### CODE REVIEW

File: src/components/ReactorEditor/useProcessJson.ts [hunk 1]
```diff
@@ -46,7 +46,7 @@ export function useProessJson({
     })
 
     return () => jsWorker.terminate()
-  }, [editorName, jsWorker])
+  }, [model, jsWorker])
```
Comment (Phryxia) [inline src/components/ReactorEditor/useProcessJson.ts:49]: Single `editorName` can have more than two remounts. Also there might be some time delay between `editorName` and `model` configured. Therefore every created model must be configured.
